services:
  mqtt-server:
    image: iegomez/mosquitto-go-auth
    container_name: mqtt-server
    volumes:
      - ./.config/:/etc/mosquitto
    ports:
      - "1883:1883"
      - "1884:1884"
    networks:
      - mqtt
    depends_on:
      - db

  db:
    image: mysql:8.0.33
    container_name: db
    volumes:
      - mqtt-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mqtt-data
    ports:
      - "3306:3306"
    networks:
      - mqtt

volumes:
  mqtt-data:

networks:
  mqtt:
    ipam:
      driver: default
